services:
  app:
    build: .
    working_dir: /app
    environment:
      - GIN_MODE=release
      - POSTGRES_USER=postgres
      - DATABASE_NAME=b3db
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8080:8080"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b3db
    command: postgres -c max_wal_size=16384MB 
    ports:
      - "5432:5432"